# Generated by Django 2.2 on 2023-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgilityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agilityclass_name', models.CharField(max_length=200)),
                ('agilityclass_description', models.CharField(max_length=1000)),
                ('agilityclass_price', models.FloatField()),
                ('agilityclass_length', models.CharField(max_length=50)),
                ('agilityclass_week1', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_message', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='NonAgilityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonagilityclass_name', models.CharField(max_length=200)),
                ('nonagilityclass_description', models.CharField(max_length=1000)),
                ('nonagilityclass_price', models.FloatField()),
                ('nonagilityclass_length', models.CharField(max_length=50)),
                ('nonagilityclass_week1', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
