# Generated by Django 2.2 on 2023-12-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_trainer_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonagilityclass',
            name='nonagilityclass_image',
            field=models.CharField(default='https://classroomclipart.com/image/static7/preview2/cartoon-dog-sitting-down-with-a-black-nose-outline-57221.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/004/629/642/original/empty-shopping-bag-free-vector.jpg', max_length=500),
        ),
    ]
