# Generated by Django 2.2 on 2023-12-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_auto_20231206_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_image',
            field=models.CharField(default='https://classroomclipart.com/image/static7/preview2/cartoon-dog-sitting-down-with-a-black-nose-outline-57221.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_week2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_week3',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_week4',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_week5',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='agilityclass',
            name='agilityclass_week6',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
